imports:
    - ../../build/config/package-container.yml
    - ../../bundle/config/package-container.yml
    - ../../cache/config/package-container.yml
    - ../../collection/config/package-container.yml
    - ../../config/config/package-container.yml
    - ../../container/config/package-container.yml
    - ../../db/config/package-container.yml
    - ../../field/config/package-container.yml
    - ../../form/config/package-container.yml
    - ../../handlebars/config/package-container.yml
    - ../../helper/config/package-container.yml
    - ../../http/config/package-container.yml
    - ../../imageresizer/config/package-container.yml
    - ../../layout/config/package-container.yml
    - ../../mail/config/package-container.yml
    - ../../language/config/package-container.yml
    - ../../person/config/package-container.yml
    - ../../pubsub/config/package-container.yml
    - ../../queue/config/package-container.yml
    - ../../route/config/package-container.yml
    - ../../search/config/package-container.yml
    - ../../secret/config/package-container.yml